# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-21 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblRent',
            fields=[
                ('id_rent', models.IntegerField(db_column='id_Rent', primary_key=True, serialize=False)),
                ('id_clients', models.IntegerField(db_column='id_Clients')),
                ('id_clientsrenter', models.IntegerField(db_column='id_ClientsRenter')),
                ('id_car', models.IntegerField(db_column='Id_Car')),
                ('dateofpickup', models.IntegerField(db_column='DateOfPickUp')),
                ('returnday', models.IntegerField(db_column='ReturnDay')),
                ('discount', models.IntegerField(db_column='Discount')),
                ('acceptence', models.IntegerField(db_column='Acceptence')),
                ('starttime', models.IntegerField(db_column='StartTime')),
                ('endtime', models.IntegerField(db_column='EndTime')),
                ('rentedtime', models.IntegerField(db_column='RentedTime')),
                ('approvalextension', models.IntegerField(db_column='ApprovalExtension')),
                ('extendedtime', models.IntegerField(db_column='ExtendedTime')),
                ('id_penalty', models.IntegerField()),
                ('isover', models.IntegerField(db_column='isOver')),
            ],
            options={
                'db_table': 'tbl_rent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblRentpreferences',
            fields=[
                ('id_clients', models.IntegerField()),
                ('firsthour', models.IntegerField(db_column='firstHour')),
                ('lasthour', models.IntegerField(db_column='lastHour')),
                ('daysbeforerent', models.IntegerField(db_column='daysBeforeRent')),
                ('mintime', models.IntegerField(db_column='minTime')),
                ('maxtime', models.IntegerField(db_column='maxTime')),
                ('id_rentpreferences', models.AutoField(db_column='id_rentPreferences', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tbl_rentpreferences',
                'managed': False,
            },
        ),
    ]
