# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-25 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentersApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationsComments',
            fields=[
                ('id_messages', models.AutoField(primary_key=True, serialize=False)),
                ('id_clientsreceiver', models.IntegerField(db_column='id_ClientsReceiver')),
                ('id_clientscommenter', models.IntegerField(db_column='id_ClientsCommenter')),
                ('comment', models.CharField(db_column='Comment', max_length=500)),
                ('rate', models.IntegerField(db_column='Rate')),
            ],
            options={
                'db_table': 'relations_comments',
                'managed': False,
            },
        ),
    ]
