# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblClients',
            fields=[
                ('id_clients', models.AutoField(db_column='id_Clients', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='FirstName', max_length=50)),
                ('lastname', models.CharField(db_column='LastName', max_length=50)),
                ('email', models.CharField(db_column='Email', max_length=50)),
                ('password', models.CharField(db_column='Password', max_length=100)),
                ('isrenter', models.IntegerField(db_column='isRenter')),
                ('age', models.IntegerField(db_column='Age')),
                ('curp', models.CharField(db_column='CURP', max_length=18)),
                ('id_address', models.IntegerField(db_column='id_Address')),
                ('imgprofilephoto', models.CharField(db_column='imgProfilePhoto', max_length=80)),
                ('fulldata', models.IntegerField(db_column='fullData')),
            ],
        ),
    ]
