# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-04 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblclients',
            name='fulldata',
            field=models.BooleanField(db_column='fullData'),
        ),
        migrations.AlterField(
            model_name='tblclients',
            name='isrenter',
            field=models.BooleanField(db_column='isRenter'),
        ),
    ]
