# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-04 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientsApp', '0002_auto_20180703_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblAddress',
            fields=[
                ('id_address', models.IntegerField(db_column='id_Address', primary_key=True, serialize=False)),
                ('zipcode', models.IntegerField(db_column='ZipCode')),
                ('country', models.CharField(db_column='Country', max_length=50)),
                ('state', models.CharField(db_column='State', max_length=50)),
                ('province', models.CharField(db_column='Province', max_length=50)),
                ('numint', models.IntegerField(blank=True, db_column='NumInt', null=True)),
            ],
            options={
                'db_table': 'tbl_address',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='tblclients',
            options={'managed': False},
        ),
    ]
