# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-04 22:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClientsApp', '0003_auto_20180704_1707'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tblclients',
            table='tbl_clients',
        ),
    ]
