# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-09 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientsApp', '0006_auto_20180903_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblDriverlicense',
            fields=[
                ('id_clients', models.IntegerField(db_column='id_Clients')),
                ('id_driverlicense', models.AutoField(db_column='id_DriverLicense', primary_key=True, serialize=False)),
                ('licensenum', models.CharField(blank=True, db_column='LicenseNum', max_length=10, null=True)),
                ('startday', models.DateField(blank=True, db_column='StartDay', null=True)),
                ('endday', models.DateField(blank=True, db_column='EndDay', null=True)),
            ],
            options={
                'db_table': 'tbl_driverlicense',
                'managed': False,
            },
        ),
    ]
