# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-25 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientsApp', '0007_tbldriverlicense'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblLocation',
            fields=[
                ('id_location', models.AutoField(primary_key=True, serialize=False)),
                ('id_clients', models.IntegerField()),
                ('lat', models.CharField(max_length=16)),
                ('lng', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'tbl_location',
                'managed': False,
            },
        ),
    ]
