# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-04 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RelationsCarimages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_car', models.IntegerField(db_column='id_Car')),
                ('urlimg', models.CharField(db_column='UrlImg', max_length=100)),
            ],
            options={
                'db_table': 'relations_carimages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RelationsCoverage',
            fields=[
                ('id_coverage', models.AutoField(db_column='id_Coverage', primary_key=True, serialize=False)),
                ('id_policy', models.IntegerField(db_column='id_Policy')),
                ('description', models.CharField(db_column='Description', max_length=50)),
                ('assurancesum', models.CharField(db_column='AssuranceSum', max_length=50)),
                ('deductibles', models.FloatField(db_column='Deductibles')),
            ],
            options={
                'db_table': 'relations_coverage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblCar',
            fields=[
                ('id_clients', models.IntegerField(db_column='id_Clients')),
                ('id_car', models.CharField(db_column='id_Car', max_length=11, primary_key=True, serialize=False)),
                ('brand', models.CharField(db_column='Brand', max_length=30)),
                ('model', models.CharField(db_column='Model', max_length=30)),
                ('year', models.IntegerField(db_column='Year')),
                ('description', models.CharField(db_column='Description', max_length=200)),
                ('specialservices', models.IntegerField(db_column='SpecialServices')),
                ('automatic', models.IntegerField(db_column='Automatic')),
                ('type', models.IntegerField(db_column='Type')),
                ('ac', models.IntegerField(db_column='AC')),
                ('doors', models.IntegerField(db_column='Doors')),
                ('turbo', models.IntegerField(db_column='Turbo')),
                ('passagers', models.IntegerField(db_column='Passagers')),
                ('numsuitcase', models.IntegerField(db_column='NumSuitCase')),
                ('kmxl', models.IntegerField(db_column='KMxL')),
                ('airbags', models.IntegerField(db_column='AirBags')),
                ('abs', models.IntegerField(db_column='ABS')),
                ('costxday', models.FloatField(db_column='CostxDay')),
                ('averagecost', models.FloatField(db_column='AverageCost')),
                ('babysit', models.IntegerField(db_column='BabySit')),
                ('childsit', models.IntegerField(db_column='ChildSit')),
                ('gps', models.IntegerField(db_column='GPS')),
                ('agerestriction', models.IntegerField(db_column='AgeRestriction')),
                ('latepolicy', models.IntegerField(db_column='LatePolicy')),
                ('rentalrestrictions', models.IntegerField(db_column='RentalRestrictions')),
                ('smokerestriction', models.IntegerField(db_column='SmokeRestriction')),
                ('audiobluetooth', models.IntegerField(db_column='AudioBluetooth')),
                ('audioaux', models.IntegerField(db_column='AudioAux')),
                ('customaudio', models.IntegerField(db_column='CustomAudio')),
                ('number_4x4', models.IntegerField(db_column='4x4')),
                ('sparetier', models.IntegerField(db_column='SpareTier')),
                ('alarm', models.IntegerField(db_column='Alarm')),
                ('sensor', models.IntegerField(db_column='Sensor')),
            ],
            options={
                'db_table': 'tbl_car',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblPolicy',
            fields=[
                ('id_policy', models.IntegerField(db_column='id_Policy', primary_key=True, serialize=False)),
                ('id_car', models.IntegerField(db_column='id_Car')),
                ('clientpolicynumber', models.IntegerField(db_column='ClientPolicyNumber')),
                ('policy', models.IntegerField(db_column='Policy')),
                ('company', models.CharField(db_column='Company', max_length=50)),
                ('cis', models.IntegerField(db_column='CIS')),
                ('clientpolicyname', models.IntegerField(db_column='ClientPolicyName')),
                ('validationdatestart', models.DateTimeField(db_column='ValidationDateStart')),
                ('validationdateend', models.DateTimeField(db_column='ValidationDateEnd')),
            ],
            options={
                'db_table': 'tbl_policy',
                'managed': False,
            },
        ),
    ]
