# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-21 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarsApp', '0002_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='remark',
            new_name='filename',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='file',
            new_name='name',
        ),
    ]
