# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-21 22:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarsApp', '0003_auto_20181021_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='name',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='filename',
            new_name='remark',
        ),
    ]
