# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-09 00:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarsApp', '0004_auto_20181021_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='remark',
            new_name='id_clients',
        ),
    ]
