# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-25 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarsApp', '0005_auto_20181108_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(db_column='file', upload_to=b'')),
                ('id_clients', models.CharField(db_column='id_clients', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_column='timestamp')),
                ('type', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_file',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
